### ISSUE TITLE
Support @Slf4j active annotation.

### ISSUE THREAD

**Issue by otrosien** [oehme/xtend-contrib#32]
Like @Log, but using slf4j LoggerFactory. Idea from project lombok ( https://projectlombok.org/api/lombok/extern/slf4j/Slf4j.html ) To avoid always pulling in slf4j, even if you're not using this annotation, I could think about two alternatives.

1. use "compileOnly" / "provided" scope for the slf4j dependency. This leaves the responsibility to the user, to make sure slf4j is on the classpath when he's using the annotation (which he needs to have anyways...) This also matches what lombok is doing.

2. extract the annotation into its own maven artifact that includes the dependency. Breaks the one-jar-fits-all packaging that is used at the moment.

What do you suggest?

**Comment by otrosien** [comment]
.. I started a feature branch (feature/logging) where there's support for Slf4j, log4j, log4j2, jcl, and jul. :)

**Comment by otrosien** [comment]
Just got an implementation idea, which is differing from lombok, but acutually makes more sense, as you'll neve be combining those logger annotations onto a single class. We could make @Log configurable with an enum (e.g. `@Log(via=LogApi.Slf4j...`).

**Comment by otrosien** [comment]
@oehme could you give some feedback? Would you rather like the idea of on Log-annotation, using annotation parameters, or distinct annotation, as in pull request #36 ?

**Comment by oehme** [comment]
I think the separate annotations are good, as that will allow us to break them into their own jars if we ever feel that xtend-contrib gets too big. In that sense, I would even put each in their own package.

**Comment by oehme** [comment]
This has been solved as part of #36. Release 1.1.0 is being built right now.
